### ISSUE TITLE
New search parameter: Ninja

### ISSUE THREAD

**Issue by l00z** [bugdone/headshotbox#128]
Would be great if you could search for rounds won by defusing with one or more terrorists still alive.

**Comment by bugdone** [comment]
What about the number of teammates alive?
Would 5 CTs vs 1 T saving the gun be a ninja?

**Comment by l00z** [comment]
I suppose limiting it to clutch situations would be sensible, though 2v5 with an ecoing teammate is of course a possibility as well. Maybe using rounds where there Ts outnumber or have the same amount of players left would be a reasonable compromise, but that in turn overly sounds complicated. 

It would still make finding those rounds significantly easier. Currently it's reliant on notes which I am too lazy to use since overall the search function is really powerful.

**Comment by bugdone** [comment]
> rounds where there Ts outnumber or have the same amount of players left 
this sounds like a decent compromise

**Comment by bugdone** [comment]
I implemented the check described above when the defuse ends (not when it starts).
Turns out some of the rounds are 2v1 where 1 CT starts defusing and the other 2 fight, the T getting the kill. Kinda underwhelming.

Looking at more than 10 rounds in my demo collection, most of them are pretty boring actually (the CT using a smoke or the T being too far). I expected more cool stuff to be honest :(
