### ISSUE TITLE
Host hsbox without port

### ISSUE THREAD

**Issue by Bl4CkGuuN** [bugdone/headshotbox#225]
Is it possible to host the hsbox without an port so you just need the domain?

**Comment by ajohnsen** [comment]
You will always need a port to host stuff online, but if you want the port not to be visible in the address bar you have to use the default http/https ports which are 80 and 443. So you can make headshotbox use port 80, or you can set up a proxy like nginx in front of it so that you can serve both a http and a https version with a proper certificate.

**Comment by Bl4CkGuuN** [comment]
Do I need to shutdown apache then?

**Comment by juho-hanhimaki** [comment]
Single port can be listened by single program only. So if your apache listens for port 80, headshotbox needs to listen for some other port. Alternatively you can shutdown any programs that use the port 80 or just change the port apache uses.

If you are using a router that is capable of port forwarding you can route whatever frontend (WAN) port to whatever backend (LAN) port. So it doesn't really matter what port the headshotbox is listening to in that scenario. Some programs might use port 80 by default so choosing to run headshotbox on some other port might be good idea to avoid any conflicts.
