### ISSUE TITLE
Add more per player and weapon stats

### ISSUE THREAD

**Issue by hellkama** [bugdone/headshotbox#78]
Some ideas for player stats:
* Entry frags (T-side)
* Opening frags (CT or T side)
* All clutch types: 1v1, 1v2, 1v3, 1v4, 1v5, 1vAll
* Bombs planted
* Bombs defused
* MVPs
* Score (points)
* Damage per round

Weapons stats:
* Shots fired
* Accuracy
* K:D while owned/used the weapon

This is definitely a great tool as is! But please keep working on it :)

**Comment by bugdone** [comment]
Bombs planted/defused, MVPs, score and shots fired seem pointless as they don't mean much. Also the more you play, the bigger the numbers.
Accuracy isn't a good idea because of wall/smoke spamming and prefiring. Probably snipers would get the highest number here.
K:D while owned/used the weapon would be interesting but it's hard to analyze. You can switch weapons just at the end of the round. Taking into account only the weapons you fired is no good also: you can also buy an awp and die in the first duel before you fire it.

Still not decided if I want to add the clutch types. Clutch win% for all the types except 1v1 would be very small.

For entry frags, I added: Entry win %, First duel win % and Entry kills per round. This makes the most sense to me. hltv.org also has Entry Rating but I have no clue how that's computed.

I plan on adding Damage per round as soon as I modify the parser to include damage events.

**Comment by hellkama** [comment]
Yep you're absolutely correct, most of that stuff is quite meaningless in terms of analysis.

However one could probably at least try observe differences in play styles of players in a team with some of those stats.

**Comment by bugdone** [comment]
Implemented ADR. Closing because I don't want to implement the rest of the stats.
